---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: debian-7.8
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[tar]
      - recipe[perl]
      - recipe[mecab]
      - recipe[mecab-perl]

